Merge changes from Rich Alderson.
PDP-10/klh10 pull request #15
Opened 2017-01-25 13:02 UTC by larsbrinkhoff

I merged the changes from Rich and resolved the conflicts.  This is the result.

I have not considered what, if anything, is useful.  I can revise this pull request based on feed back.

2017-01-26 01:10 UTC, brouhaha commented
Most of it looks fine to me, but I think the replacement of $(.TARGETS) in a makefile with an explicit list of targets might be undesirable. However, I haven't studied the makefiles enough to be sure. Maybe it's worth asking Rich why he changed that.

2017-01-26 06:01 UTC, larsbrinkhoff commented
Note that old/src/Mk-fbppc.mk also has an explicit list.  Are the files in "old" used at all?

2017-01-26 08:26 UTC, brouhaha commented
I have no idea whether the files in "old" are used, but if they're not, there's no point in merging changes to them.

2017-01-26 20:54 UTC, Rhialto commented
No, the files in "old" are not used any more. I kept them only for reference, mainly for the different options there are for building the different models.

Removing the dvlites.o module from the KS models can be done now as well, without further changes. Back when these patches were made, the `#ifdef`s checking `KLH10_DEV_LITES` had to be moved a bit to exclude code related to that more thoroughly. You will see for example that the patch to `klh10.c` now supplies `fc_lights(struct cmd_s *cm)` with a double set of `#ifdef`s.

In `kn10pag.c` there is an exclusion of some header files and a call (to that doubly-guarded function). The `dvlites.h` header file has its internal guard so it can always be included. The other two header files are needed in any case, because clang complains about implicit function declarations.

In `osdsup.c`, there is the constant `IPC_PRIVATE` which I looked at before, and concluded that it was used incorrectly at that location.

I can either simply remove the lites object file from the makefile and consider the changes merged. Or you could remove the duplicated `KLH10_DEV_LITES` guard, choosing the "outer" or "more thorough" exclusion, and restore the include files, and make that into a new pull request.

2017-01-27 05:55 UTC, larsbrinkhoff commented
@Rhialto Can you post line-by-line comments indicating what changes you want?

2017-01-27 20:06 UTC, Rhialto commented on old/src/Mk-fbx86.mk
No: This file is unused, and CENV_CPU_I686 doesn't occur anywhere else either.
The other changes to this file are unwanted for the first reason as well.

2017-01-27 20:07 UTC, Rhialto commented on src/Makefile.mk
YES. This we can do. If somebody adds lights to the KS (is that even sensible?) it is easy enough to add it again.

2017-01-27 20:09 UTC, Rhialto commented on src/klh10.c
YES to these 2 changes, But remove the inner ifdefs, and move the comment on the `#endif` to the remaining endif.

2017-01-27 20:10 UTC, Rhialto commented on src/kn10pag.c
>  #include "dvlites.h"
The #endif should be here. The other 2 includes should be unconditional.

2017-01-27 20:13 UTC, Rhialto commented on src/kn10pag.c
> +#endif
YES. These additions are ok. (Although, looking carefully, also not needed, since the header file, if it is included, stubs out this call anyway).

2017-01-27 20:14 UTC, Rhialto requested changes
See inline comments.

2017-01-27 20:14 UTC, Rhialto commented on src/osdsup.c
>  	fprintf(stderr, "[os_mmcreate: shmget failed for %ld bytes - %s]\n",
No. The added IPC_PRIVATE is incorrect in this location.

2017-01-27 21:10 UTC, larsbrinkhoff commented
Ok, that should be it, I think.

2017-01-29 15:16 UTC, Rhialto approved these changes

2017-01-29 15:17 UTC, merged